# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_deleted"], name="notificatio_user_id_7f1d1b_idx"),
        ),
    ]
